
unit;
public

{
  Automatically converted by H2Pas 0.99.16 from sql.h
  The following command line parameters were used:
    -d
    -c
    -p
    sql.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}

Type
PSQLCHAR  = ptr SQLCHAR;
PSQLHANDLE  = ptr SQLHANDLE;
PSQLHDBC  = ptr SQLHDBC;
PSQLHENV  = ptr SQLHENV;
PSQLHSTMT  =ptr SQLHSTMT;
PSQLINTEGER  =ptr SQLINTEGER;
PSQLLEN  = ptr SQLLEN;
PSQLPOINTER  = ptr SQLPOINTER;
PSQLSMALLINT  =ptr SQLSMALLINT;
PSQLULEN  = ptr SQLULEN;
PSQLUSMALLINT  = ptr SQLUSMALLINT;


const
   SQL_NULL_DATA = -(1);   
   SQL_DATA_AT_EXEC = -(2);   
   SQL_SUCCESS = 0;   
   SQL_SUCCESS_WITH_INFO = 1;   
   SQL_NO_DATA = 100;   
   SQL_ERROR = -(1);   
   SQL_INVALID_HANDLE = -(2);   
   SQL_STILL_EXECUTING = 2;   
   SQL_NEED_DATA = 99;   

   SQL_NTS = -(3);   
   SQL_NTSL = -(3);   

   SQL_MAX_MESSAGE_LENGTH = 512;   { maximum message length  }


const
   SQL_DATE_LEN = 10;   
   SQL_TIME_LEN = 8;   
   SQL_TIMESTAMP_LEN = 19;   

   SQL_HANDLE_ENV = 1;   
   SQL_HANDLE_DBC = 2;   
   SQL_HANDLE_STMT = 3;   
   SQL_HANDLE_DESC = 4;   

const
   SQL_ATTR_OUTPUT_NTS = 10001;   
   SQL_ATTR_AUTO_IPD = 10001;   
   SQL_ATTR_METADATA_ID = 10014; 
   SQL_ATTR_APP_ROW_DESC = 10010;   
   SQL_ATTR_APP_PARAM_DESC = 10011;   
   SQL_ATTR_IMP_ROW_DESC = 10012;   
   SQL_ATTR_IMP_PARAM_DESC = 10013;   
   SQL_ATTR_CURSOR_SCROLLABLE = -(1);   
   SQL_ATTR_CURSOR_SENSITIVITY = -(2);   

   SQL_NONSCROLLABLE = 0;   
   SQL_SCROLLABLE = 1;   

   SQL_DESC_COUNT = 1001;   
   SQL_DESC_TYPE = 1002;   
   SQL_DESC_LENGTH = 1003;   
   SQL_DESC_OCTET_LENGTH_PTR = 1004;   
   SQL_DESC_PRECISION = 1005;   
   SQL_DESC_SCALE = 1006;   
   SQL_DESC_DATETIME_INTERVAL_CODE = 1007;   
   SQL_DESC_NULLABLE = 1008;   
   SQL_DESC_INDICATOR_PTR = 1009;   
   SQL_DESC_DATA_PTR = 1010;   
   SQL_DESC_NAME = 1011;   
   SQL_DESC_UNNAMED = 1012;   
   SQL_DESC_OCTET_LENGTH = 1013;   
   SQL_DESC_ALLOC_TYPE = 1099;   

const
   SQL_DIAG_RETURNCODE = 1;   
   SQL_DIAG_NUMBER = 2;   
   SQL_DIAG_ROW_COUNT = 3;   
   SQL_DIAG_SQLSTATE = 4;   
   SQL_DIAG_NATIVE = 5;   
   SQL_DIAG_MESSAGE_TEXT = 6;   
   SQL_DIAG_DYNAMIC_FUNCTION = 7;   
   SQL_DIAG_CLASS_ORIGIN = 8;   
   SQL_DIAG_SUBCLASS_ORIGIN = 9;   
   SQL_DIAG_CONNECTION_NAME = 10;   
   SQL_DIAG_SERVER_NAME = 11;   
   SQL_DIAG_DYNAMIC_FUNCTION_CODE = 12;   

const
   SQL_DIAG_ALTER_DOMAIN = 3;   
   SQL_DIAG_ALTER_TABLE = 4;   
   SQL_DIAG_CALL = 7;   
   SQL_DIAG_CREATE_ASSERTION = 6;   
   SQL_DIAG_CREATE_CHARACTER_SET = 8;   
   SQL_DIAG_CREATE_COLLATION = 10;   
   SQL_DIAG_CREATE_DOMAIN = 23;   
   SQL_DIAG_CREATE_INDEX = -(1);   
   SQL_DIAG_CREATE_SCHEMA = 64;   
   SQL_DIAG_CREATE_TABLE = 77;   
   SQL_DIAG_CREATE_TRANSLATION = 79;   
   SQL_DIAG_CREATE_VIEW = 84;   
   SQL_DIAG_DELETE_WHERE = 19;   
   SQL_DIAG_DROP_ASSERTION = 24;   
   SQL_DIAG_DROP_CHARACTER_SET = 25;   
   SQL_DIAG_DROP_COLLATION = 26;   
   SQL_DIAG_DROP_DOMAIN = 27;   
   SQL_DIAG_DROP_INDEX = -(2);   
   SQL_DIAG_DROP_SCHEMA = 31;   
   SQL_DIAG_DROP_TABLE = 32;   
   SQL_DIAG_DROP_TRANSLATION = 33;   
   SQL_DIAG_DROP_VIEW = 36;   
   SQL_DIAG_DYNAMIC_DELETE_CURSOR = 38;   
   SQL_DIAG_DYNAMIC_UPDATE_CURSOR = 81;   
   SQL_DIAG_GRANT = 48;   
   SQL_DIAG_INSERT = 50;   
   SQL_DIAG_REVOKE = 59;   
   SQL_DIAG_SELECT_CURSOR = 85;   
   SQL_DIAG_UNKNOWN_STATEMENT = 0;   
   SQL_DIAG_UPDATE_WHERE = 82;   
const
   SQL_UNKNOWN_TYPE = 0;   
   SQL_CHAR = 1;   
   SQL_NUMERIC = 2;   
   SQL_DECIMAL = 3;   
   SQL_INTEGER = 4;   
   SQL_SMALLINT = 5;   
   SQL_FLOAT = 6;   
   SQL_REAL = 7;   
   SQL_DOUBLE = 8;   

   SQL_DATETIME = 9;   

   SQL_VARCHAR = 12;   


   SQL_TYPE_DATE = 91;   
   SQL_TYPE_TIME = 92;   
   SQL_TYPE_TIMESTAMP = 93;   

   SQL_UNSPECIFIED = 0;   
   SQL_INSENSITIVE = 1;   
   SQL_SENSITIVE = 2;   
   SQL_ALL_TYPES = 0;   
   SQL_DEFAULT = 99;   
   SQL_ARD_TYPE = -(99);   
   SQL_CODE_DATE = 1;   
   SQL_CODE_TIME = 2;   
   SQL_CODE_TIMESTAMP = 3;   

   SQL_FALSE = 0;   
   SQL_TRUE = 1;   

   SQL_NO_NULLS = 0;   
   SQL_NULLABLE = 1;   
   SQL_NULLABLE_UNKNOWN = 2;   

   SQL_PRED_NONE = 0;   
   SQL_PRED_CHAR = 1;   
   SQL_PRED_BASIC = 2;   

   SQL_NAMED = 0;   
   SQL_UNNAMED = 1;   

   SQL_DESC_ALLOC_AUTO = 1;   
   SQL_DESC_ALLOC_USER = 2;   

   SQL_CLOSE = 0;   
   SQL_DROP = 1;   
   SQL_UNBIND = 2;   
   SQL_RESET_PARAMS = 3;   

   SQL_FETCH_NEXT = 1;   
   SQL_FETCH_FIRST = 2;   
   SQL_FETCH_LAST = 3;   
   SQL_FETCH_PRIOR = 4;   
   SQL_FETCH_ABSOLUTE = 5;   
   SQL_FETCH_RELATIVE = 6;   

   SQL_COMMIT = 0;   
   SQL_ROLLBACK = 1;   
   SQL_NULL_HENV = 0;   
   SQL_NULL_HDBC = 0;   
   SQL_NULL_HSTMT = 0;   
   SQL_NULL_HDESC = 0;   
   SQL_NULL_HANDLE = 0;   

   SQL_SCOPE_CURROW = 0;   
   SQL_SCOPE_TRANSACTION = 1;   
   SQL_SCOPE_SESSION = 2;   
   SQL_PC_UNKNOWN = 0;   

const
   SQL_PC_NON_PSEUDO = 1;   

const
   SQL_PC_PSEUDO = 2;   
   SQL_ROW_IDENTIFIER = 1;   
   SQL_INDEX_UNIQUE = 0;   
   SQL_INDEX_ALL = 1;   
   SQL_INDEX_CLUSTERED = 1;   
   SQL_INDEX_HASHED = 2;   
   SQL_INDEX_OTHER = 3;   
   SQL_API_SQLALLOCCONNECT = 1;   
   SQL_API_SQLALLOCENV = 2;   


   SQL_API_SQLALLOCHANDLE = 1001;   
   SQL_API_SQLALLOCSTMT = 3;   
   SQL_API_SQLBINDCOL = 4;   

   SQL_API_SQLBINDPARAM = 1002;   

   SQL_API_SQLCANCEL = 5;   


const
   SQL_API_SQLCLOSECURSOR = 1003;   
   SQL_API_SQLCOLATTRIBUTE = 6;   


const
   SQL_API_SQLCOLUMNS = 40;   
   SQL_API_SQLCONNECT = 7;   


const
   SQL_API_SQLCOPYDESC = 1004;   


const
   SQL_API_SQLDATASOURCES = 57;   
   SQL_API_SQLDESCRIBECOL = 8;   
   SQL_API_SQLDISCONNECT = 9;   

const
   SQL_API_SQLENDTRAN = 1005;   
{$endif}

const
   SQL_API_SQLERROR = 10;   
   SQL_API_SQLEXECDIRECT = 11;   
   SQL_API_SQLEXECUTE = 12;   
   SQL_API_SQLFETCH = 13;   


const
   SQL_API_SQLFETCHSCROLL = 1021;   


const
   SQL_API_SQLFREECONNECT = 14;   
   SQL_API_SQLFREEENV = 15;   


const
   SQL_API_SQLFREEHANDLE = 1006;   
{$endif}

const
   SQL_API_SQLFREESTMT = 16;   
const
   SQL_API_SQLGETCONNECTATTR = 1007;   


const
   SQL_API_SQLGETCONNECTOPTION = 42;   
   SQL_API_SQLGETCURSORNAME = 17;   
   SQL_API_SQLGETDATA = 43;   


const
   SQL_API_SQLGETDESCFIELD = 1008;   
   SQL_API_SQLGETDESCREC = 1009;   
   SQL_API_SQLGETDIAGFIELD = 1010;   
   SQL_API_SQLGETDIAGREC = 1011;   
   SQL_API_SQLGETENVATTR = 1012;   


const
   SQL_API_SQLGETFUNCTIONS = 44;   
   SQL_API_SQLGETINFO = 45;   


const
   SQL_API_SQLGETSTMTATTR = 1014;   


const
   SQL_API_SQLGETSTMTOPTION = 46;   
   SQL_API_SQLGETTYPEINFO = 47;   
   SQL_API_SQLNUMRESULTCOLS = 18;   
   SQL_API_SQLPARAMDATA = 48;   
   SQL_API_SQLPREPARE = 19;   
   SQL_API_SQLPUTDATA = 49;   
   SQL_API_SQLROWCOUNT = 20;   


const
   SQL_API_SQLSETCONNECTATTR = 1016;   


const
   SQL_API_SQLSETCONNECTOPTION = 50;   
   SQL_API_SQLSETCURSORNAME = 21;   


const
   SQL_API_SQLSETDESCFIELD = 1017;   
   SQL_API_SQLSETDESCREC = 1018;   
   SQL_API_SQLSETENVATTR = 1019;   


const
   SQL_API_SQLSETPARAM = 22;   


const
   SQL_API_SQLSETSTMTATTR = 1020;   


const
   SQL_API_SQLSETSTMTOPTION = 51;   
   SQL_API_SQLSPECIALCOLUMNS = 52;   
   SQL_API_SQLSTATISTICS = 53;   
   SQL_API_SQLTABLES = 54;   
   SQL_API_SQLTRANSACT = 23;   

const
   SQL_MAX_DRIVER_CONNECTIONS = 0;   
   SQL_MAXIMUM_DRIVER_CONNECTIONS = SQL_MAX_DRIVER_CONNECTIONS;   
   SQL_MAX_CONCURRENT_ACTIVITIES = 1;   
   SQL_MAXIMUM_CONCURRENT_ACTIVITIES = SQL_MAX_CONCURRENT_ACTIVITIES;   


const
   SQL_DATA_SOURCE_NAME = 2;   
   SQL_FETCH_DIRECTION = 8;   
   SQL_SERVER_NAME = 13;   
   SQL_SEARCH_PATTERN_ESCAPE = 14;   
   SQL_DBMS_NAME = 17;   
   SQL_DBMS_VER = 18;   
   SQL_ACCESSIBLE_TABLES = 19;   
   SQL_ACCESSIBLE_PROCEDURES = 20;   
   SQL_CURSOR_COMMIT_BEHAVIOR = 23;   
   SQL_DATA_SOURCE_READ_ONLY = 25;   
   SQL_DEFAULT_TXN_ISOLATION = 26;   
   SQL_IDENTIFIER_CASE = 28;   
   SQL_IDENTIFIER_QUOTE_CHAR = 29;   
   SQL_MAX_COLUMN_NAME_LEN = 30;   
   SQL_MAXIMUM_COLUMN_NAME_LENGTH = SQL_MAX_COLUMN_NAME_LEN;   
   SQL_MAX_CURSOR_NAME_LEN = 31;   
   SQL_MAXIMUM_CURSOR_NAME_LENGTH = SQL_MAX_CURSOR_NAME_LEN;   
   SQL_MAX_SCHEMA_NAME_LEN = 32;   
   SQL_MAXIMUM_SCHEMA_NAME_LENGTH = SQL_MAX_SCHEMA_NAME_LEN;   
   SQL_MAX_CATALOG_NAME_LEN = 34;   
   SQL_MAXIMUM_CATALOG_NAME_LENGTH = SQL_MAX_CATALOG_NAME_LEN;   
   SQL_MAX_TABLE_NAME_LEN = 35;   
   SQL_SCROLL_CONCURRENCY = 43;   
   SQL_TXN_CAPABLE = 46;   
   SQL_TRANSACTION_CAPABLE = SQL_TXN_CAPABLE;   
   SQL_USER_NAME = 47;   
   SQL_TXN_ISOLATION_OPTION = 72;   
   SQL_TRANSACTION_ISOLATION_OPTION = SQL_TXN_ISOLATION_OPTION;   
   SQL_INTEGRITY = 73;   
   SQL_GETDATA_EXTENSIONS = 81;   
   SQL_NULL_COLLATION = 85;   
   SQL_ALTER_TABLE = 86;   
   SQL_ORDER_BY_COLUMNS_IN_SELECT = 90;   
   SQL_SPECIAL_CHARACTERS = 94;   
   SQL_MAX_COLUMNS_IN_GROUP_BY = 97;   
   SQL_MAXIMUM_COLUMNS_IN_GROUP_BY = SQL_MAX_COLUMNS_IN_GROUP_BY;   
   SQL_MAX_COLUMNS_IN_INDEX = 98;   
   SQL_MAXIMUM_COLUMNS_IN_INDEX = SQL_MAX_COLUMNS_IN_INDEX;   
   SQL_MAX_COLUMNS_IN_ORDER_BY = 99;   
   SQL_MAXIMUM_COLUMNS_IN_ORDER_BY = SQL_MAX_COLUMNS_IN_ORDER_BY;   
   SQL_MAX_COLUMNS_IN_SELECT = 100;   
   SQL_MAXIMUM_COLUMNS_IN_SELECT = SQL_MAX_COLUMNS_IN_SELECT;   
   SQL_MAX_COLUMNS_IN_TABLE = 101;   
   SQL_MAX_INDEX_SIZE = 102;   
   SQL_MAXIMUM_INDEX_SIZE = SQL_MAX_INDEX_SIZE;   
   SQL_MAX_ROW_SIZE = 104;   
   SQL_MAXIMUM_ROW_SIZE = SQL_MAX_ROW_SIZE;   
   SQL_MAX_STATEMENT_LEN = 105;   
   SQL_MAXIMUM_STATEMENT_LENGTH = SQL_MAX_STATEMENT_LEN;   
   SQL_MAX_TABLES_IN_SELECT = 106;   
   SQL_MAXIMUM_TABLES_IN_SELECT = SQL_MAX_TABLES_IN_SELECT;   
   SQL_MAX_USER_NAME_LEN = 107;   
   SQL_MAXIMUM_USER_NAME_LENGTH = SQL_MAX_USER_NAME_LEN;   


const
   SQL_OJ_CAPABILITIES = 115;   
   SQL_OUTER_JOIN_CAPABILITIES = SQL_OJ_CAPABILITIES;   

const
   SQL_XOPEN_CLI_YEAR = 10000;   
   SQL_CURSOR_SENSITIVITY = 10001;   
   SQL_DESCRIBE_PARAMETER = 10002;   
   SQL_CATALOG_NAME = 10003;   
   SQL_COLLATION_SEQ = 10004;   
   SQL_MAX_IDENTIFIER_LEN = 10005;   
   SQL_MAXIMUM_IDENTIFIER_LENGTH = SQL_MAX_IDENTIFIER_LEN;   

   SQL_AT_ADD_COLUMN = $00000001;   
   SQL_AT_DROP_COLUMN = $00000002;   

   SQL_AT_ADD_CONSTRAINT = $00000008;   

   SQL_AM_NONE = 0;   
   SQL_AM_CONNECTION = 1;   
   SQL_AM_STATEMENT = 2;   

   SQL_CB_DELETE = 0;   
   SQL_CB_CLOSE = 1;   
   SQL_CB_PRESERVE = 2;   

   SQL_FD_FETCH_NEXT = $00000001;   
   SQL_FD_FETCH_FIRST = $00000002;   
   SQL_FD_FETCH_LAST = $00000004;   
   SQL_FD_FETCH_PRIOR = $00000008;   
   SQL_FD_FETCH_ABSOLUTE = $00000010;   
   SQL_FD_FETCH_RELATIVE = $00000020;   

   SQL_GD_ANY_COLUMN = $00000001;   
   SQL_GD_ANY_ORDER = $00000002;   

   SQL_IC_UPPER = 1;   
   SQL_IC_LOWER = 2;   
   SQL_IC_SENSITIVE = 3;   
   SQL_IC_MIXED = 4;   

const
   SQL_OJ_LEFT = $00000001;   
   SQL_OJ_RIGHT = $00000002;   
   SQL_OJ_FULL = $00000004;   
   SQL_OJ_NESTED = $00000008;   
   SQL_OJ_NOT_ORDERED = $00000010;   
   SQL_OJ_INNER = $00000020;   
   SQL_OJ_ALL_COMPARISON_OPS = $00000040;   

const
   SQL_SCCO_READ_ONLY = $00000001;   
   SQL_SCCO_LOCK = $00000002;   
   SQL_SCCO_OPT_ROWVER = $00000004;   
   SQL_SCCO_OPT_VALUES = $00000008;   
{ SQL_TXN_CAPABLE values  }
   SQL_TC_NONE = 0;   
   SQL_TC_DML = 1;   
   SQL_TC_ALL = 2;   
   SQL_TC_DDL_COMMIT = 3;   
   SQL_TC_DDL_IGNORE = 4;   
{ SQL_TXN_ISOLATION_OPTION bitmasks  }
   SQL_TXN_READ_UNCOMMITTED = $00000001;   
   SQL_TRANSACTION_READ_UNCOMMITTED = SQL_TXN_READ_UNCOMMITTED;   
   SQL_TXN_READ_COMMITTED = $00000002;   
   SQL_TRANSACTION_READ_COMMITTED = SQL_TXN_READ_COMMITTED;   
   SQL_TXN_REPEATABLE_READ = $00000004;   
   SQL_TRANSACTION_REPEATABLE_READ = SQL_TXN_REPEATABLE_READ;   
   SQL_TXN_SERIALIZABLE = $00000008;   
   SQL_TRANSACTION_SERIALIZABLE = SQL_TXN_SERIALIZABLE;   
{ SQL_NULL_COLLATION values  }
   SQL_NC_HIGH = 0;   
   SQL_NC_LOW = 1;   

external lib 'ODBC'
function SQLAllocConnect(EnvironmentHandle:SQLHENV; ConnectionHandle:PSQLHDBC):SQLRETURN;
function SQLAllocEnv(EnvironmentHandle:PSQLHENV):SQLRETURN;

function SQLAllocStmt(ConnectionHandle:SQLHDBC; StatementHandle:PSQLHSTMT):SQLRETURN;
function SQLBindCol(StatementHandle:SQLHSTMT; ColumnNumber:SQLUSMALLINT; TargetType:SQLSMALLINT; TargetValue:SQLPOINTER; BufferLength:SQLLEN; 
           StrLen_or_Ind:PSQLLEN):SQLRETURN;
function SQLCancel(StatementHandle:SQLHSTMT):SQLRETURN;

function SQLColumns(StatementHandle:SQLHSTMT; CatalogName:PSQLCHAR; NameLength1:SQLSMALLINT; SchemaName:PSQLCHAR; NameLength2:SQLSMALLINT; 
           TableName:PSQLCHAR; NameLength3:SQLSMALLINT; ColumnName:PSQLCHAR; NameLength4:SQLSMALLINT):SQLRETURN;
function SQLConnect(ConnectionHandle:SQLHDBC; ServerName:PSQLCHAR; NameLength1:SQLSMALLINT; UserName:PSQLCHAR; NameLength2:SQLSMALLINT; 
           Authentication:PSQLCHAR; NameLength3:SQLSMALLINT):SQLRETURN;

function SQLDataSources(EnvironmentHandle:SQLHENV; Direction:SQLUSMALLINT; ServerName:PSQLCHAR; BufferLength1:SQLSMALLINT; NameLength1:PSQLSMALLINT; 
           Description:PSQLCHAR; BufferLength2:SQLSMALLINT; NameLength2:PSQLSMALLINT):SQLRETURN;
function SQLDescribeCol(StatementHandle:SQLHSTMT; ColumnNumber:SQLUSMALLINT; ColumnName:PSQLCHAR; BufferLength:SQLSMALLINT; NameLength:PSQLSMALLINT; 
           DataType:PSQLSMALLINT; ColumnSize:PSQLULEN; DecimalDigits:PSQLSMALLINT; Nullable:PSQLSMALLINT):SQLRETURN;
function SQLDisconnect(ConnectionHandle:SQLHDBC):SQLRETURN;

function SQLError(EnvironmentHandle:SQLHENV; ConnectionHandle:SQLHDBC; StatementHandle:SQLHSTMT; Sqlstate:PSQLCHAR; NativeError:PSQLINTEGER; 
           MessageText:PSQLCHAR; BufferLength:SQLSMALLINT; TextLength:PSQLSMALLINT):SQLRETURN;
function SQLExecDirect(StatementHandle:SQLHSTMT; StatementText:PSQLCHAR; TextLength:SQLINTEGER):SQLRETURN;
function SQLExecute(StatementHandle:SQLHSTMT):SQLRETURN;
function SQLFetch(StatementHandle:SQLHSTMT):SQLRETURN;

function SQLFreeConnect(ConnectionHandle:SQLHDBC):SQLRETURN;
function SQLFreeEnv(EnvironmentHandle:SQLHENV):SQLRETURN;

function SQLFreeStmt(StatementHandle:SQLHSTMT; Option:SQLUSMALLINT):SQLRETURN;

function SQLGetConnectOption(ConnectionHandle:SQLHDBC; Option:SQLUSMALLINT; Value:SQLPOINTER):SQLRETURN;
function SQLGetCursorName(StatementHandle:SQLHSTMT; CursorName:PSQLCHAR; BufferLength:SQLSMALLINT; NameLength:PSQLSMALLINT):SQLRETURN;
function SQLGetData(StatementHandle:SQLHSTMT; ColumnNumber:SQLUSMALLINT; TargetType:SQLSMALLINT; TargetValue:SQLPOINTER; BufferLength:SQLLEN; 
           StrLen_or_Ind:PSQLLEN):SQLRETURN;

function SQLGetFunctions(ConnectionHandle:SQLHDBC; FunctionId:SQLUSMALLINT; Supported:PSQLUSMALLINT):SQLRETURN;
function SQLGetInfo(ConnectionHandle:SQLHDBC; InfoType:SQLUSMALLINT; InfoValue:SQLPOINTER; BufferLength:SQLSMALLINT; StringLength:PSQLSMALLINT):SQLRETURN;

function SQLGetStmtOption(StatementHandle:SQLHSTMT; Option:SQLUSMALLINT; Value:SQLPOINTER):SQLRETURN;
function SQLGetTypeInfo(StatementHandle:SQLHSTMT; DataType:SQLSMALLINT):SQLRETURN;
function SQLNumResultCols(StatementHandle:SQLHSTMT; ColumnCount:PSQLSMALLINT):SQLRETURN;
function SQLParamData(StatementHandle:SQLHSTMT; Value:PSQLPOINTER):SQLRETURN;
function SQLPrepare(StatementHandle:SQLHSTMT; StatementText:PSQLCHAR; TextLength:SQLINTEGER):SQLRETURN;
function SQLPutData(StatementHandle:SQLHSTMT; Data:SQLPOINTER; StrLen_or_Ind:SQLLEN):SQLRETURN;
function SQLRowCount(StatementHandle:SQLHSTMT; RowCount:PSQLLEN):SQLRETURN;

function SQLSetConnectOption(ConnectionHandle:SQLHDBC; Option:SQLUSMALLINT; Value:SQLULEN):SQLRETURN;
function SQLSetCursorName(StatementHandle:SQLHSTMT; CursorName:PSQLCHAR; NameLength:SQLSMALLINT):SQLRETURN;

function SQLSetParam(StatementHandle:SQLHSTMT; ParameterNumber:SQLUSMALLINT; ValueType:SQLSMALLINT; ParameterType:SQLSMALLINT; LengthPrecision:SQLULEN; 
           ParameterScale:SQLSMALLINT; ParameterValue:SQLPOINTER; StrLen_or_Ind:PSQLLEN):SQLRETURN;

function SQLSetStmtOption(StatementHandle:SQLHSTMT; Option:SQLUSMALLINT; Value:SQLROWCOUNT):SQLRETURN;
function SQLSpecialColumns(StatementHandle:SQLHSTMT; IdentifierType:SQLUSMALLINT; CatalogName:PSQLCHAR; NameLength1:SQLSMALLINT; SchemaName:PSQLCHAR; 
           NameLength2:SQLSMALLINT; TableName:PSQLCHAR; NameLength3:SQLSMALLINT; Scope:SQLUSMALLINT; Nullable:SQLUSMALLINT):SQLRETURN;
function SQLStatistics(StatementHandle:SQLHSTMT; CatalogName:PSQLCHAR; NameLength1:SQLSMALLINT; SchemaName:PSQLCHAR; NameLength2:SQLSMALLINT; 
           TableName:PSQLCHAR; NameLength3:SQLSMALLINT; Unique:SQLUSMALLINT; Reserved:SQLUSMALLINT):SQLRETURN;
function SQLTables(StatementHandle:SQLHSTMT; CatalogName:PSQLCHAR; NameLength1:SQLSMALLINT; SchemaName:PSQLCHAR; NameLength2:SQLSMALLINT; 
           TableName:PSQLCHAR; NameLength3:SQLSMALLINT; TableType:PSQLCHAR; NameLength4:SQLSMALLINT):SQLRETURN;
function SQLTransact(EnvironmentHandle:SQLHENV; ConnectionHandle:SQLHDBC; CompletionType:SQLUSMALLINT):SQLRETURN;

{ODBCVER >= 0x0300}


function SQLAllocHandle(HandleType:SQLSMALLINT; InputHandle:SQLHANDLE; OutputHandle:PSQLHANDLE):SQLRETURN;

function SQLCloseCursor(StatementHandle:SQLHSTMT):SQLRETURN;
function SQLColAttribute(StatementHandle:SQLHSTMT; ColumnNumber:SQLUSMALLINT; FieldIdentifier:SQLUSMALLINT; CharacterAttribute:SQLPOINTER; BufferLength:SQLSMALLINT; 
           StringLength:PSQLSMALLINT; NumericAttribute:SQLPOINTER):SQLRETURN;

function SQLCopyDesc(SourceDescHandle:SQLHDESC; TargetDescHandle:SQLHDESC):SQLRETURN;
function SQLFetchScroll(StatementHandle:SQLHSTMT; FetchOrientation:SQLSMALLINT; FetchOffset:SQLROWOFFSET):SQLRETURN;
function SQLEndTran(HandleType:SQLSMALLINT; Handle:SQLHANDLE; CompletionType:SQLSMALLINT):SQLRETURN;
function SQLFreeHandle(HandleType:SQLSMALLINT; Handle:SQLHANDLE):SQLRETURN;
function SQLGetConnectAttr(ConnectionHandle:SQLHDBC; Attribute:SQLINTEGER; Value:SQLPOINTER; BufferLength:SQLINTEGER; StringLength:PSQLINTEGER):SQLRETURN;
function SQLGetDescField(DescriptorHandle:SQLHDESC; RecNumber:SQLSMALLINT; FieldIdentifier:SQLSMALLINT; Value:SQLPOINTER; BufferLength:SQLINTEGER; 
           StringLength:PSQLINTEGER):SQLRETURN;
function SQLGetDescRec(DescriptorHandle:SQLHDESC; RecNumber:SQLSMALLINT; Name:PSQLCHAR; BufferLength:SQLSMALLINT; StringLength:PSQLSMALLINT; 
           _Type:PSQLSMALLINT; SubType:PSQLSMALLINT; Length:PSQLLEN; Precision:PSQLSMALLINT; Scale:PSQLSMALLINT; 
           Nullable:PSQLSMALLINT):SQLRETURN;
function SQLGetDiagField(HandleType:SQLSMALLINT; Handle:SQLHANDLE; RecNumber:SQLSMALLINT; DiagIdentifier:SQLSMALLINT; DiagInfo:SQLPOINTER; 
           BufferLength:SQLSMALLINT; StringLength:PSQLSMALLINT):SQLRETURN;
function SQLGetDiagRec(HandleType:SQLSMALLINT; Handle:SQLHANDLE; RecNumber:SQLSMALLINT; Sqlstate:PSQLCHAR; NativeError:PSQLINTEGER; 
           MessageText:PSQLCHAR; BufferLength:SQLSMALLINT; TextLength:PSQLSMALLINT):SQLRETURN;
function SQLGetEnvAttr(EnvironmentHandle:SQLHENV; Attribute:SQLINTEGER; Value:SQLPOINTER; BufferLength:SQLINTEGER; StringLength:PSQLINTEGER):SQLRETURN;
function SQLGetStmtAttr(StatementHandle:SQLHSTMT; Attribute:SQLINTEGER; Value:SQLPOINTER; BufferLength:SQLINTEGER; StringLength:PSQLINTEGER):SQLRETURN;
function SQLSetStmtAttr(StatementHandle:SQLHSTMT; Attribute:SQLINTEGER; Value:SQLPOINTER; StringLength:SQLINTEGER):SQLRETURN;
function SQLSetConnectAttr(ConnectionHandle:SQLHDBC; Attribute:SQLINTEGER; Value:SQLPOINTER; StringLength:SQLINTEGER):SQLRETURN;
function SQLSetDescField(DescriptorHandle:SQLHDESC; RecNumber:SQLSMALLINT; FieldIdentifier:SQLSMALLINT; Value:SQLPOINTER; BufferLength:SQLINTEGER):SQLRETURN;
function SQLSetDescRec(DescriptorHandle:SQLHDESC; RecNumber:SQLSMALLINT; _Type:SQLSMALLINT; SubType:SQLSMALLINT; Length:SQLLEN; 
           Precision:SQLSMALLINT; Scale:SQLSMALLINT; Data:SQLPOINTER; StringLength:PSQLLEN; Indicator:PSQLLEN):SQLRETURN;
function SQLSetEnvAttr(EnvironmentHandle:SQLHENV; Attribute:SQLINTEGER; Value:SQLPOINTER; StringLength:SQLINTEGER):SQLRETURN;

function SQLBindParam(StatementHandle:SQLHSTMT; ParameterNumber:SQLUSMALLINT; ValueType:SQLSMALLINT; ParameterType:SQLSMALLINT; LengthPrecision:SQLULEN; 
           ParameterScale:SQLSMALLINT; ParameterValue:SQLPOINTER; StrLen_or_Ind:PSQLLEN):SQLRETURN;


end;

implementation



end.
