all:
	$(MAKE) all -C data
	$(MAKE) all -C files
	$(MAKE) all -C db
	$(MAKE) all -C gui

install:
	$(MAKE) install -C data
	$(MAKE) install -C files
	$(MAKE) install -C db
	$(MAKE) install -C gui

clean:
	$(MAKE) clean -C data
	$(MAKE) clean -C files
	$(MAKE) clean -C db
	$(MAKE) clean -C gui
